<?php

return [
    'aguas-claras' => [
        'slug' => 'aguas-claras',
        'nome' => 'Águas Claras',
        'nome_completo' => 'Shopp Reparos Águas Claras',
        'titulo' => 'Shopp Reparos Águas Claras — Ferragens, Hidráulica, Elétrica e Ferramentas',
        'descricao' => 'Loja de ferragens, materiais hidráulicos, elétricos e ferramentas em Águas Claras — Brasília/DF. Consulte endereço, horário, telefone, WhatsApp e como chegar.',
        'endereco' => 'Q 204 Alfa Mix Loja 15A',
        'bairro' => 'Águas Claras',
        'cidade' => 'Brasília',
        'uf' => 'DF',
        'cep' => '71939-540',
        'telefone' => '(61) 99609-6296',
        'telefone_e164' => '+5561996096296',
        'whatsapp' => '5561996096296',
        'horario_semana' => 'Segunda a sexta: 8h às 18h',
        'horario_sabado' => 'Sábado: 8h às 14h',
        'horario_resumo' => 'Seg a Sex: 8h às 18h | Sáb: 8h às 14h',
        'imagem' => 'img/Lojas/aguasclaras.webp',
        'maps_embed' => 'https://www.google.com/maps?q=Q%20204%20Alfa%20Mix%20Loja%2015A%2C%20%C3%81guas%20Claras%2C%20Bras%C3%ADlia%20-%20DF%2C%2071939-540&output=embed',
        'maps_url' => 'https://www.google.com/maps/search/?api=1&query=Q+204+Alfa+Mix+Loja+15A,+Águas+Claras,+Brasília+-+DF,+71939-540',
        'destaque' => 'Loja principal',
    ],
    'taguatinga' => [
        'slug' => 'taguatinga',
        'nome' => 'Taguatinga',
        'nome_completo' => 'Shopp Reparos Taguatinga',
        'titulo' => 'Shopp Reparos Taguatinga — Ferragens, Hidráulica, Elétrica e Ferramentas',
        'descricao' => 'Loja de ferragens, material hidráulico, elétrico e ferramentas em Taguatinga Sul — Brasília/DF. Consulte endereço, horário, telefone, WhatsApp e como chegar.',
        'endereco' => 'CSE 02 Loja 19 - Taguatinga Sul',
        'bairro' => 'Taguatinga Sul',
        'cidade' => 'Brasília',
        'uf' => 'DF',
        'cep' => '72025-025',
        'telefone' => '(61) 99931-8077',
        'telefone_e164' => '+5561999318077',
        'whatsapp' => '5561999318077',
        'horario_semana' => 'Segunda a sexta: 8h às 18h',
        'horario_sabado' => 'Sábado: 8h às 14h',
        'horario_resumo' => 'Seg a Sex: 8h às 18h | Sáb: 8h às 14h',
        'imagem' => 'img/Lojas/taguatinga.webp',
        'maps_embed' => 'https://www.google.com/maps?q=CSE%2002%20Loja%2019%20-%20Taguatinga%20Sul%2C%20Bras%C3%ADlia%20-%20DF&output=embed',
        'maps_url' => 'https://www.google.com/maps/search/?api=1&query=CSE+02+Loja+19,+Taguatinga+Sul,+Brasília+-+DF',
        'destaque' => 'Taguatinga Sul',
    ],
];
